[minio]
endpoint = http://minio:9000
access_key = admin
secret_key = password
path_style_access = true
credentials_provider = org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
bronze_path = s3a://lakehouse/cold-chain-telemetry/bronze
silver_path = s3a://lakehouse/cold-chain-telemetry/silver
gold_path = s3a://lakehouse/cold-chain-telemetry/gold
